name = "Nystrom"
uuid = "33e8372d-7e06-487f-b481-26071f42257e"
authors = ["Luiz M. Faria  <maltezfaria@gmail.com>, Carlos Perez-Arancibia  <caperezar@gmail.com>"]
version = "0.1.0"

[deps]
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
